# fly.toml app configuration file generated for cmc-api on 2023-08-14T15:26:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cmc-api"
primary_region = "yul"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
